### ISSUE TITLE
[infra] Erro ao tentar atualizar dataset recém criado (Python 3.9)

### ISSUE THREAD

**Issue by mfagundes** [basedosdados/mais#1062]
**Descrição**
Após criar um dataset localmente, atualizei o arquivo dataset_config.yaml e, ao rodar o código 

```basedosdados dataset update [DATASET_ID]```  

retorna ``ValueError`` (Traceback completo abaixo)

**Reproduzir**
Passos para reproduzir o comportamento:
1. Inicializar um dataset: ``basedosdados dataset init [DATASET_ID]``
2. Criar o dataset no BigQuery: ``basedosdados dataset create [DATASET_ID]``
3. Alterar as configurações no arquivo ``dataset_config.yaml``
4. Atualizar o dataset ``basedosdados dataset update [DATASET_ID]``

**Comportamento esperado**
Atualizar os dados inseridos no arquivo no Google BigQuery

**Desktop:**
  - MacBook Pro M1 (Apple Silicon)
  - SO: macOS 11.6.2 (Big Sur)
  - virtualenv com Python 3.9
  - basedosdados versão 1.6.1

**Contexto adicional**
Este é o primeiro dado que crio. Gerei apenas o dataset, ainda não gerei as tabelas

**Traceback completo**
```
Traceback (most recent call last):
  File "/Users/mauricio/virtualenvs/mais/bin/basedosdados", line 8, in <module>
    sys.exit(cli())
  File "/Users/mauricio/virtualenvs/mais/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mauricio/virtualenvs/mais/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/mauricio/virtualenvs/mais/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mauricio/virtualenvs/mais/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mauricio/virtualenvs/mais/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mauricio/virtualenvs/mais/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mauricio/virtualenvs/mais/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mauricio/virtualenvs/mais/lib/python3.9/site-packages/basedosdados/cli/cli.py", line 101, in update_dataset
    Dataset(dataset_id=dataset_id, **ctx.obj).update(mode=mode)
  File "/Users/mauricio/virtualenvs/mais/lib/python3.9/site-packages/basedosdados/upload/dataset.py", line 214, in update
    dataset = m["client"].update_dataset(
  File "/Users/mauricio/virtualenvs/mais/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 1072, in update_dataset
    partial = dataset._build_resource(fields)
  File "/Users/mauricio/virtualenvs/mais/lib/python3.9/site-packages/google/cloud/bigquery/dataset.py", line 704, in _build_resource
    return _helpers._build_resource_from_properties(self, filter_fields)
  File "/Users/mauricio/virtualenvs/mais/lib/python3.9/site-packages/google/cloud/bigquery/_helpers.py", line 924, in _build_resource_from_properties
    raise ValueError("No property %s" % filter_field)
ValueError: No property description
```

**Comment by mfagundes** [comment]
Acho que esta issue já está superada e deveria ser fechada @lucascr91 @d116626
