### ISSUE TITLE
[infra] Description error after `table publish`

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/mais#511]
**Describe the bug**
`table publish` is throwing a `description.txt` error after `table publish` 

**To Reproduce**
1. Create a brand-new table, it can be very simple
2. Do not populate metadata 
3. Publish it with `table publish`

**Expected behavior**
No errors were expected

**Additional context**
Traceback

```
$ basedosdados table publish data-test table-test --if_exists replace
Traceback (most recent call last):
  File "/Users/ryancarroll/.local/share/virtualenvs/brazil-datalake-ttzOJ48i/bin/basedosdados", line 8, in <module>
    sys.exit(cli())
  File "/Users/ryancarroll/.local/share/virtualenvs/brazil-datalake-ttzOJ48i/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ryancarroll/.local/share/virtualenvs/brazil-datalake-ttzOJ48i/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ryancarroll/.local/share/virtualenvs/brazil-datalake-ttzOJ48i/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ryancarroll/.local/share/virtualenvs/brazil-datalake-ttzOJ48i/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ryancarroll/.local/share/virtualenvs/brazil-datalake-ttzOJ48i/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ryancarroll/.local/share/virtualenvs/brazil-datalake-ttzOJ48i/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ryancarroll/.local/share/virtualenvs/brazil-datalake-ttzOJ48i/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ryancarroll/.local/share/virtualenvs/brazil-datalake-ttzOJ48i/lib/python3.8/site-packages/basedosdados/cli/cli.py", line 326, in publish_table
    Table(table_id=table_id, dataset_id=dataset_id, **ctx.obj).publish(
  File "/Users/ryancarroll/.local/share/virtualenvs/brazil-datalake-ttzOJ48i/lib/python3.8/site-packages/basedosdados/upload/table.py", line 565, in publish
    self.update("prod")
  File "/Users/ryancarroll/.local/share/virtualenvs/brazil-datalake-ttzOJ48i/lib/python3.8/site-packages/basedosdados/upload/table.py", line 517, in update
    open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ryancarroll/google_drive/code/brazil-datalake/bases/data_test/table_test/table_description.txt'
```

**Comment by JoaoCarabetta** [comment]
I just tested with the exact same data and I couldn't reproduce it.
