### ISSUE TITLE
[infra] Bug: `tomlkit.exceptions.KeyAlreadyPresent: Key "url" already exists.`

### ISSUE THREAD

**Issue by rdahis** [basedosdados/mais#995]
**Descrição**
Erro novo após tentar criar uma tabela ou metadados.

**Reproduzir**
Passos para reproduzir o comportamento:

Rodar `basedosdados table create br_fl_programas municipio --path "/Users/ricardodahis/Dropbox/Academic/Data/Brazil/FL/Programas/output/municipio.csv"`

ou rodar `basedosdados metadata create br_fl_programas municipio`.

**Capturas de tela**

```sh
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/basedosdados", line 8, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/basedosdados/cli/cli.py", line 253, in create_table
    Table(table_id=table_id, dataset_id=dataset_id, **ctx.obj).create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/basedosdados/upload/table.py", line 32, in __init__
    super().__init__(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/basedosdados/upload/base.py", line 31, in __init__
    self.config = self._load_config()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/basedosdados/upload/base.py", line 303, in _load_config
    return tomlkit.parse(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tomlkit/api.py", line 51, in parse
    return Parser(string).parse()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tomlkit/parser.py", line 160, in parse
    key, value = self._parse_table()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tomlkit/parser.py", line 1159, in _parse_table
    table.raw_append(_key, item)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tomlkit/items.py", line 948, in raw_append
    self._value.append(key, _item)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tomlkit/container.py", line 187, in append
    raise KeyAlreadyPresent(key)
tomlkit.exceptions.KeyAlreadyPresent: Key "url" already exists.
```

**Comment by d116626** [comment]
parece que o problema a no arquivo  `~/.basedosdados/config.toml`, passa ele ai, só remove o secret do ckan

**Comment by rdahis** [comment]
Resolvido! Era um argumento `url` definido duas vezes.
